name: Auto Pull

on:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run pull script
        run: ./pull.sh
